### ISSUE TITLE
How to download nebula.v1.0.0_2018_11_23.tar.gz, I can't find by Google.

### ISSUE THREAD

**Issue by ExpOrx** [threathunterX/nebula_doc#1]
<img width="786" alt="Screen Shot 2019-03-11 at 3 33 35 PM" src="https://user-images.githubusercontent.com/18424387/54107073-1510ca00-4413-11e9-934e-e1c871a23d53.png">

**Comment by threathunterX** [comment]
fixed some doc error in chapter1/section1.md
